version: '3.7'
services:
  postgres:
    image: postgres:13
    hostname: postgres
    container_name: Your_App_Name
    restart: always
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: Your_Volume_Name
